### ISSUE TITLE
Warning: Error in as.character: cannot coerce type 'closure' to vector of type 'character'

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#74] opened 2024-05-24 21:03 UTC
With https://github.com/ashokkrish/episim/commit/300bac6f6beb4b0c1568934fa8b8a2cbce29a09e, running the SIR model results in the warning quoted in the issue name.

**Comment by bryce-carson** [comment] 2024-05-25 17:29
@Toby-exe, this is related to your modifications to SIR plotter. We will need to meet (virtually) and work synchronously to resolve the present issues related to plotting.

**Comment by bryce-carson** [comment] 2024-05-28 21:38
@Toby-exe, I have taken a little walk in the code away from this error. When I was fixing the unified model solvers I encountered plenty of other errors related to what I was doing and fixing. I am confident I have finished my work, as I see this error once again. Have your latest changes fixed this issue? If so, please go ahead and close it.

**Comment by Toby-exe** [comment] 2024-05-28 21:42
The problem is I don't even get this error no matter which model I try to run. I try to run any SI type model I get the "integration steps..." error but all the SEI type models do run for me without errors. I checked with Khanh and she also get the same error as you and ashok so not sure why its different for me.

**Comment by bryce-carson** [comment] 2024-05-28 22:21
That's quite odd! I'll review your changes to the SIR plotting functions, and if this issue was resolved by them I will close it, since you're not able to reproduce it.

**Comment by Toby-exe** [comment] 2024-05-28 22:23
you most recent commit has fixed these issues for me

**Comment by bryce-carson** [comment] 2024-05-28 22:25
> you most recent commit has fixed these issues for me

The errors related to "integration steps..." and illegal options/inputs that _deSolve::lsoda_ was throwing? Great.

**Comment by Toby-exe** [comment] 2024-05-28 22:27
> > you most recent commit has fixed these issues for me
> 
> The errors related to "integration steps..." and illegal options/inputs that _deSolve::lsoda_ was throwing? Great.

yup all gone. I can run any model now.

**Comment by bryce-carson** [comment] 2024-05-28 22:30
> > > you most recent commit has fixed these issues for me
> > 
> > 
> > The errors related to "integration steps..." and illegal options/inputs that _deSolve::lsoda_ was throwing? Great.
> 
> yup all gone. I can run any model now.

Excellent. I was just about to test my changes. I have been working on organizational tasks and emails since I completed the rebase and pushed my changes this afternoon. Does the error quoted in the issue title appear? Any other warnings? Please go ahead and create issues for anything you notice, or close anything you know is now outdated (updating issue titles and creating tasklists in issue descriptions [opening comment] and/or marking tasks as complete in tasklists is also valid).

**Comment by Toby-exe** [comment] 2024-05-28 22:36
> > > > you most recent commit has fixed these issues for me
> > > 
> > > 
> > > The errors related to "integration steps..." and illegal options/inputs that _deSolve::lsoda_ was throwing? Great.
> > 
> > 
> > yup all gone. I can run any model now.
> 
> Excellent. I was just about to test my changes. I have been working on organizational tasks and emails since I completed the rebase and pushed my changes this afternoon. Does the error quoted in the issue title appear? Any other warnings? Please go ahead and create issues for anything you notice, or close anything you know is now outdated (updating issue titles and creating tasklists in issue descriptions [opening comment] and/or marking tasks as complete in tasklists is also valid).

Absolutely zero errors when I run the app, regardless of which model I choose.

**Closed** 2024-05-31 04:10 UTC
