### ISSUE TITLE
Warning messages appear when switching over to a Stochastic model

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#133] opened 2024-06-27 07:32 UTC
The following Warning messages appear when switching over to a Stochastic model. @kle6951 Can you take care of fixing all of these asap please?

```
Warning: `aes_string()` was deprecated in ggplot2 3.0.0.
ℹ Please use tidy evaluation idioms with `aes()`.
ℹ See also `vignette("ggplot2-in-packages")` for more information.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.
Warning: Using an external vector in selections was deprecated in tidyselect 1.1.0.
ℹ Please use `all_of()` or `any_of()` instead.
  # Was:
  data %>% select(compartments)

  # Now:
  data %>% select(all_of(compartments))

See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.
```

**Comment by kle6951** [comment] 2024-06-27 09:06
@ashokkrish this warning message shouldn't be treated as a bug since it just informs us the function we are using right now will be obsolete at some point in the future. I will leave this issue as open as I will look into the issue early tomorrow morning to determine whether I can turn this message off. Otherwise, it is just warning information. It shouldn't be a big issue or treated as a bug for your presentation.

**Comment by bryce-carson** [comment] 2024-06-27 16:54
I'm closing this as a duplicate of #129. @kle6951, please read my suggestion in #129 about resolving this warning.

**Closed** 2024-06-27 16:55 UTC
